### ISSUE TITLE
[FRONTEND] Layout à mettre en place

### ISSUE THREAD

**Issue by charafzellou** [ulyhmyges/DEX#4]
Votre layout de Frontend n'a aucun composant sur vos pages.

Il vous faut accélérer le rythme pour avoir une base à afficher avec votre backend.

Pensez à utiliser des composants simples au début, afin d'afficher le minimum pour avancer.

**Comment by ulyhmyges** [comment]
- Layout dans le main.
- Branches features (front-swap, docs et connectwallet) remergées dans la branche develop.
- Pull request de la branche develop sur la base main.
